### ISSUE TITLE
Add a tiny GitHub Actions job that fires only on PRs opened by Dependabot, runs your scripts/sync-requirements-txt.sh, and force-pushes any change back into that PR

### ISSUE THREAD

**Issue by jiridanek** [opendatahub-io/notebooks#1191]
@jiridanek  
Add a tiny GitHub Actions job that fires only on PRs opened by Dependabot, runs your `scripts/sync-requirements-txt.sh`, and force-pushes any change back into that PR:

```yaml
# .github/workflows/regenerate-requirements.yml
name: Regenerate requirements.txt in Dependabot PR

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]              # adjust if needed

jobs:
  sync-reqs:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write             # allow the job to push back
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}   # checkout the PR branch
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps for the script (if any)
        run: pip install pipenv
      - name: Regenerate requirements.txt
        run: ./scripts/sync-requirements-txt.sh
      - name: Commit & push
        run: |
          git config user.email "actions@github.com"
          git config user.name  "github-actions"
          if ! git diff --quiet; then
            git commit -am "ci: sync requirements.txt"
            git push
          fi
```

Flow:

1. Dependabot updates `Pipfile.lock` → opens PR.  
2. Action triggers, checks‐out that PR branch.  
3. Your script recreates `requirements.txt` (with hashes).  
4. If the file changed, the job commits & pushes, so the PR contains both files in sync—no manual fixes.

_Originally posted by @coderabbitai in https://github.com/opendatahub-io/notebooks/pull/1126#discussion_r2167045838_
