### ISSUE TITLE
[EPIC] [QA] Test the VS Code & R studio Notebooks

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#260]
The images are already available on the ODH clusters.
- [ ] If using the V2 Operator of ODH.
    The image should be available the default.
- [ ] If using the V1 operator of ODH.
https://github.com/opendatahub-io/odh-manifests/tree/7e98dd18cc7e2a61872038dc955f710ae6bf7c14/notebook-images/overlays/additional
    ```
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: notebook-images
        overlays:
        - additional
      name: notebook-images
     ``` 

Minimum tests required:

- [x] #365
- [x] #364
