### ISSUE TITLE
[CodeSever] liveness and readiness probe times out due extension installation

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#421]
There is a problem with this approach and current Notebooks when installing more than just these few extensions at runtime. The [defaults for liveness and readiness probe times come from odh-dashboard, I think, when assembling the notebook CR.](https://github.com/shalberd/odh-dashboard/blob/c0dca01fa32691e45cef37cb7c84471950e193c8/frontend/src/api/k8s/notebooks.ts#L150)

```
          name: code-server-vs
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/dstst-analytix-fraud/code-server-vs/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
```

Because installing extensions takes some time at the code-server-vs/api health check endpoint is not up and running until after all extensions install and the nginx http server is running, the container keeps re-starting without more than 5 or 6 extensions ever installed.

I solved this by patching the notebook CR to have a large initialDelaySeconds of 100, so then code server started.

What do you think? @guimou do you have an idea of how to circumvent this problem of premature container restart due to failing liveness probes when installing more than, say, 6 or 7 extensions?

_Originally posted by @shalberd in https://github.com/opendatahub-io/notebooks/pull/347#discussion_r1495055841_
