### ISSUE TITLE
tune openshift/release jobs resource requests for all the various pods

### ISSUE THREAD

**Issue by jiridanek** [opendatahub-io/notebooks#952]
this is what we have in src-amd64, which is a clear overkill

```
  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: '2'
      ephemeral-storage: 120Gi
      memory: 2Gi
```

when I tried to set this up, with the `'*'` thing, it did not work for me, the alternate override requests seemed to be ignored and all pods had the base requests

<img width="1319" alt="Image" src="https://github.com/user-attachments/assets/687a35af-9d57-45de-8f95-341e76ecb5df" />

* [ ] https://github.com/openshift/release/pull/62861
